### ISSUE TITLE
Koppeling vakken

### ISSUE THREAD

**Issue by allardstrijkerslo** [slonl/curriculum-examenprogramma#1]
Het is niet duidelijk hoe de koppeling tussen de vakken in de examenprogramma's is en bijvoorbeeld leerplan in beeld

**Comment by poef** [comment]
Examenprogramma heeft ondertussen een verwijzing naar ExamenprogrammaVakleergebied, die weer verwijst naar Vakleergebied. Die laatste koppelt met andere specifiek vakleergebieden, zoals de KerndoelVakleergebied en LdkVakleergebied. Daarmee is Vakleergebied de gemene deler geworden.
