### ISSUE TITLE
Eindtermen missen bij subdomeinen

### ISSUE THREAD

**Issue by allardstrijkerslo** [slonl/curriculum-examenprogramma#2]
https://opendata.slo.nl/curriculum/api-acpt/v1/examenprogramma/
https://opendata.slo.nl/curriculum/api-acpt/v1/uuid/f6d0da70-f3f4-4165-b700-3cc5bc1bb1cd/ levert niks op

**Comment by HoldYourWaffle** [comment]
Dit lijkt inmiddels gefixt te zijn:
![image](https://github.com/slonl/curriculum-examenprogramma/assets/11472320/10910f3d-1055-4b3f-a3f4-0f6d7bd8bc52)

**Comment by poef** [comment]
De acceptatie omgeving wordt automatisch bijgewerkt als er wijzigingen in de datasets zijn. Op zo'n moment kan deze even (2 minuten ofzo) uit de lucht zijn. Duurt dit langer dan is er iets anders aan de hand.
