### ISSUE TITLE
Typering eindtermen klopt niet

### ISSUE THREAD

**Issue by allardstrijkerslo** [slonl/curriculum-examenprogramma#3]
https://opendata.slo.nl/curriculum/api-acpt/v1/uuid/70024571-16da-4d8b-ac17-1dea6e865af3/
 Type: ExamenprogrammaEindterm klopt niet, Dit hoort Globale eindterm te zijn.

**Comment by HoldYourWaffle** [comment]
Is dit nog relevant?
Wat is precies het verschil tussen een ExamenprogrammaEindterm en een Globale eindterm?

**Comment by poef** [comment]
De term 'ExamenprogrammaEindterm' is een naam die in de dataset betekenis heeft. 'Globale eindterm' is dat niet. Dat is een vakjargon term. Het kan zijn dat deze twee equivalent zijn, dat durf ik als techneut niet te bevestigen. In het algemeen is het technisch zo opgezet dat elke context (set van samenhangende gegevens) een eigen 'prefix' heeft. Dat is hier 'Examenprogramma'. Alle termen hierbinnen beginnen met deze prefix. Bij de syllabus hebben we bijv. een 'SyllabusSpecifiekeEindterm'. Mijn vermoeden is dat 'Globale eindterm' in de dataset vertaald is naar 'ExamenprogrammaEindterm'. Misschien was 'ExamenprogrammaGlobaleEindterm' dan duidelijker geweest. Maar voor de details moet je dan toch bij de inhoudelijke experts van SLO zijn.
