### ISSUE TITLE
Relaties van eindtermen is niet te zien, parent en niveau worden niet getoond

### ISSUE THREAD

**Issue by allardstrijkerslo** [slonl/curriculum-examenprogramma#4]
https://opendata.slo.nl/curriculum/api-acpt/v1/uuid/70024571-16da-4d8b-ac17-1dea6e865af3/
Er is niet aangegeven wat de parent en niveau is van de eindterm. Dit maakt controleren onmogelijk.

**Comment by HoldYourWaffle** [comment]
Dit lijkt inmiddels gefixt te zijn:
![image](https://github.com/slonl/curriculum-examenprogramma/assets/11472320/faed88be-0986-4eae-8e1d-00550d67dab5)

**Comment by poef** [comment]
Er is afgelopen week een release van de 2024 dataset gedaan, daarmee is de data voor de acceptatie omgeving ook aangepast. Misschien dat daarmee dit probleem verholpen is? Het valt me op dat de url die je opgaf nu naar een deprecated item wijst. Maar bij de nieuwe (vervangen door) link lijkt alles ook goed te staan. Toch bedankt voor het meekijken.
